### PR TITLE
Sigils

### PR DESCRIPTION
**Pull request by pfrazee**
Update to prefix message keys with the `%` sigil

### CODE REVIEW

**Comment by dominictarr** [comment]
is the author a sigil link? it should be i think

**Comment by pfrazee** [comment]
@dominictarr yes, it is

**Comment by pfrazee** [comment]
that's facilitated by changes to `ssb-keys`, https://github.com/ssbc/ssb-keys/pull/19

**Comment by dominictarr** [comment]
okay cool :+1:

**Pull request merged**
