### PR TITLE
use monotonic timestamp, incase the messages are generated really fast

### PR DESCRIPTION
**Pull request by dominictarr**
fixes this problem: https://github.com/ssbc/ssb-keys/pull/14#issuecomment-106810472

backwards compatible.

### CODE REVIEW

**Comment by pfrazee** [comment]
This makes sense but it sucks for app developers, since it means they need to massage the value before feeding it into `Date()`. No big deal, but are there alternatives?

**Comment by dominictarr** [comment]
if they are using publish via ssb-client they don't need to manage this, if they have a key for their own app then they run this code in their program so again it's cool.

**Comment by dominictarr** [comment]
but the other option is to change this https://github.com/ssbc/secure-scuttlebutt/blob/master/validation.js#L78 so that it allows equal timestamps. I'd rather have increasing timestamps though

**Comment by pfrazee** [comment]
actually I was thinking of the apps reading existing message timestamps

>  I'd rather have increasing timestamps though

Why? doesn't the `seq` encode what we need for order?

**Comment by pfrazee** [comment]
nm it is compatible still, :+1:

**Comment by dominictarr** [comment]
```
<domanic> pfraze, this change is backwards compatible - it only appends the decimal part if two timestamps are within the same milisecond
<domanic> this means we can use the timestamp for ordering messages
<domanic> if we want
<pfraze> domanic: oh, I was under the impression it appended a dash-<num>
<pfraze> ok that works
<domanic> no it's still a double
<domanic> pfraze, okay I'll merge that then?
<pfraze> sure
```

**Comment by dominictarr** [comment]
merged into 0.1.0

**Pull request merged**
